---
- hosts: iis
  gather_facts: no
  vars_files:
    - /opt/devopsys/ansible/inventarios/group_vars/windows.yml

  tasks:
  - name: Instalando Chocolatey
    win_chocolatey:
      name: procexp
      state: present
...
